### ISSUE TITLE
Тормозная кнопка "Зарегистрироваться"

### ISSUE THREAD

**Issue by kirikaza** [rozhkovdmitrii/ski73#8]
После нажатия кнопки "зарегистрироваться" непонятно, что происходит. Возможно, стоит деактивировать (или скрывать) эту кнопку, а также выводить сообщение "сейчас вылетит птичка". Можно симпатичную крутящуюся фиговину показывать.

**Comment by rozhkovdmitrii** [comment]
При обработке запроса на регистрацию форма лочится.
